// THIS FILE IS AUTO GENERATED

/* eslint-disable */

export enum IconNames {
  'accountant' = 'accountant',
  'addDocument' = 'addDocument',
  'addImage' = 'addImage',
  'arrow-down' = 'arrow-down',
  'arrowBack' = 'arrowBack',
  'arrowDown' = 'arrowDown',
  'arrowForward' = 'arrowForward',
  'arrowUpRight' = 'arrowUpRight',
  'bank' = 'bank',
  'bankHistory' = 'bankHistory',
  'category' = 'category',
  'chevronDown' = 'chevronDown',
  'close' = 'close',
  'coin' = 'coin',
  'download' = 'download',
  'emptyDocument' = 'emptyDocument',
  'envelopeStars' = 'envelopeStars',
  'expense' = 'expense',
  'eye' = 'eye',
  'hamburger' = 'hamburger',
  'hrm' = 'hrm',
  'infoCircle' = 'infoCircle',
  'information' = 'information',
  'invoice' = 'invoice',
  'logout' = 'logout',
  'mail' = 'mail',
  'notification' = 'notification',
  'percentage' = 'percentage',
  'printer' = 'printer',
  'report' = 'report',
  'sales' = 'sales',
  'setting' = 'setting',
  'tax' = 'tax',
  'thumbsUp' = 'thumbsUp'
}
